---
title: تثبيت وحدة picozero من غير الاتصال بالأنترنت
hero_image: images/banner.png
description: تثبيت picozero إذا لم تتمكن من التثبيت بواسطة مدير حزم "Thonny".
version: 4
listed: false
copyedit: false
last_tested: "2022-03-22"
steps:
  - title: تثبيت وحدة picozero من غير الاتصال بالأنترنت
